# themes.py
# Define multiple color themes for the Tkinter app

THEMES = {
    # Modern Dark (Dracula inspired)
    "Modern Dark": {
        "bg": "#282a36",
        "fg": "#f8f8f2",
        "button_bg": "#44475a",
        "button_fg": "#f8f8f2",
        "entry_bg": "#343746",
        "entry_fg": "#f8f8f2",
        "select_bg": "#6272a4",
        "select_fg": "#f8f8f2",
        "highlight": "#bd93f9",
        "widget_bg": "#343746",
        "widget_fg": "#f8f8f2",
    },
    # Classic Light
    "Classic Light": {
        "bg": "#f8f8f2",
        "fg": "#23272e",
        "button_bg": "#e0e0e0",
        "button_fg": "#23272e",
        "entry_bg": "#ffffff",
        "entry_fg": "#23272e",
        "select_bg": "#b3d7ff",
        "select_fg": "#23272e",
        "highlight": "#50fa7b",
        "widget_bg": "#f0f0f0",
        "widget_fg": "#23272e",
    },
    # Solarized Dark
    "Solarized Dark": {
        "bg": "#002b36",
        "fg": "#93a1a1",
        "button_bg": "#073642",
        "button_fg": "#93a1a1",
        "entry_bg": "#073642",
        "entry_fg": "#93a1a1",
        "select_bg": "#586e75",
        "select_fg": "#fdf6e3",
        "highlight": "#b58900",
        "widget_bg": "#073642",
        "widget_fg": "#93a1a1",
    },
    # Solarized Light
    "Solarized Light": {
        "bg": "#fdf6e3",
        "fg": "#657b83",
        "button_bg": "#eee8d5",
        "button_fg": "#657b83",
        "entry_bg": "#ffffff",
        "entry_fg": "#657b83",
        "select_bg": "#b3d7ff",
        "select_fg": "#657b83",
        "highlight": "#268bd2",
        "widget_bg": "#eee8d5",
        "widget_fg": "#657b83",
    },
    # Pastel
    "Pastel": {
        "bg": "#ffe5ec",
        "fg": "#6d6875",
        "button_bg": "#b8c0ff",
        "button_fg": "#22223b",
        "entry_bg": "#f3c4fb",
        "entry_fg": "#6d6875",
        "select_bg": "#b8c0ff",
        "select_fg": "#22223b",
        "highlight": "#f4978e",
        "widget_bg": "#ffe5ec",
        "widget_fg": "#6d6875",
    },
    # Forest
    "Forest": {
        "bg": "#232b2b",
        "fg": "#d9ead3",
        "button_bg": "#4e944f",
        "button_fg": "#f0fff1",
        "entry_bg": "#386641",
        "entry_fg": "#f0fff1",
        "select_bg": "#6a994e",
        "select_fg": "#232b2b",
        "highlight": "#a7c957",
        "widget_bg": "#386641",
        "widget_fg": "#d9ead3",
    },
    # Ocean
    "Ocean": {
        "bg": "#102542",
        "fg": "#f9f9f9",
        "button_bg": "#1b3b6f",
        "button_fg": "#f9f9f9",
        "entry_bg": "#1b3b6f",
        "entry_fg": "#f9f9f9",
        "select_bg": "#278ea5",
        "select_fg": "#102542",
        "highlight": "#21e6c1",
        "widget_bg": "#1b3b6f",
        "widget_fg": "#f9f9f9",
    },
    # High Contrast
    "High Contrast": {
        "bg": "#000000",
        "fg": "#ffffff",
        "button_bg": "#000000",
        "button_fg": "#ffffff",
        "entry_bg": "#222222",
        "entry_fg": "#ffffff",
        "select_bg": "#ffff00",
        "select_fg": "#000000",
        "highlight": "#ff0080",
        "widget_bg": "#222222",
        "widget_fg": "#ffffff",
    },
    # Monokai
    "Monokai": {
        "bg": "#272822",
        "fg": "#f8f8f2",
        "button_bg": "#75715e",
        "button_fg": "#f8f8f2",
        "entry_bg": "#49483e",
        "entry_fg": "#f8f8f2",
        "select_bg": "#a6e22e",
        "select_fg": "#272822",
        "highlight": "#fd971f",
        "widget_bg": "#49483e",
        "widget_fg": "#f8f8f2",
    },
    # Material
    "Material": {
        "bg": "#263238",
        "fg": "#eeffff",
        "button_bg": "#37474f",
        "button_fg": "#eeffff",
        "entry_bg": "#2e3c43",
        "entry_fg": "#eeffff",
        "select_bg": "#80cbc4",
        "select_fg": "#263238",
        "highlight": "#ffcb6b",
        "widget_bg": "#37474f",
        "widget_fg": "#eeffff",
    },
    # Pink Lemonade
    "Pink Lemonade": {
        "bg": "#fff0f6",
        "fg": "#ad1457",
        "button_bg": "#f06292",
        "button_fg": "#fff0f6",
        "entry_bg": "#f8bbd0",
        "entry_fg": "#ad1457",
        "select_bg": "#f06292",
        "select_fg": "#fff0f6",
        "highlight": "#e75480",
        "widget_bg": "#f8bbd0",
        "widget_fg": "#ad1457",
    },
    # Mint
    "Mint": {
        "bg": "#e0f2f1",
        "fg": "#004d40",
        "button_bg": "#26a69a",
        "button_fg": "#e0f2f1",
        "entry_bg": "#b2dfdb",
        "entry_fg": "#004d40",
        "select_bg": "#26a69a",
        "select_fg": "#e0f2f1",
        "highlight": "#80cbc4",
        "widget_bg": "#b2dfdb",
        "widget_fg": "#004d40",
    },
    # Slate
    "Slate": {
        "bg": "#23272e",
        "fg": "#c9d1d9",
        "button_bg": "#3b4252",
        "button_fg": "#c9d1d9",
        "entry_bg": "#2e3440",
        "entry_fg": "#c9d1d9",
        "select_bg": "#81a1c1",
        "select_fg": "#23272e",
        "highlight": "#88c0d0",
        "widget_bg": "#2e3440",
        "widget_fg": "#c9d1d9",
    },
    # Grape
    "Grape": {
        "bg": "#f3e8ff",
        "fg": "#5e548e",
        "button_bg": "#9f86c0",
        "button_fg": "#f3e8ff",
        "entry_bg": "#be95c4",
        "entry_fg": "#5e548e",
        "select_bg": "#9f86c0",
        "select_fg": "#f3e8ff",
        "highlight": "#e0b1cb",
        "widget_bg": "#be95c4",
        "widget_fg": "#5e548e",
    },
    # Tangerine
    "Tangerine": {
        "bg": "#fff4e6",
        "fg": "#ff8800",
        "button_bg": "#ffb347",
        "button_fg": "#fff4e6",
        "entry_bg": "#ffe5b4",
        "entry_fg": "#ff8800",
        "select_bg": "#ffb347",
        "select_fg": "#fff4e6",
        "highlight": "#ff8800",
        "widget_bg": "#ffe5b4",
        "widget_fg": "#ff8800",
    },
    # Sky Blue
    "Sky Blue": {
        "bg": "#e3f6fd",
        "fg": "#1565c0",
        "button_bg": "#90caf9",
        "button_fg": "#e3f6fd",
        "entry_bg": "#bbdefb",
        "entry_fg": "#1565c0",
        "select_bg": "#90caf9",
        "select_fg": "#e3f6fd",
        "highlight": "#039be5",
        "widget_bg": "#bbdefb",
        "widget_fg": "#1565c0",
    },
    # Lemon Fresh
    "Lemon Fresh": {
        "bg": "#f9fbe7",
        "fg": "#827717",
        "button_bg": "#fbc02d",
        "button_fg": "#f9fbe7",
        "entry_bg": "#fffde7",
        "entry_fg": "#827717",
        "select_bg": "#fbc02d",
        "select_fg": "#f9fbe7",
        "highlight": "#ffd600",
        "widget_bg": "#fffde7",
        "widget_fg": "#827717",
    },
    # Rose Gold
    "Rose Gold": {
        "bg": "#fff1f2",
        "fg": "#b76e79",
        "button_bg": "#f7cac9",
        "button_fg": "#fff1f2",
        "entry_bg": "#f7cac9",
        "entry_fg": "#b76e79",
        "select_bg": "#f7cac9",
        "select_fg": "#fff1f2",
        "highlight": "#deafb6",
        "widget_bg": "#f7cac9",
        "widget_fg": "#b76e79",
    },
}
